# TODO please replace ?must? config value

# todo [database] ip/port/username/password ?must?
austin:
  database:
    ip: localhost
    port: 3306
    username: root
    password: wdmm8611

##################### database properties #####################
# notice:mysql version 5.7x !!!
spring:
  datasource:
    url: jdbc:mysql://${austin.database.ip}:${austin.database.port}/austin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${austin.database.username}
    password: ${austin.database.password}
    driver-class-name: com.mysql.jdbc.Driver